"""fix appointment time column

Revision ID: 0606f738e792
Revises: 50c899d2e488
Create Date: 2026-06-03 11:40:18.536757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0606f738e792'
down_revision: Union[str, Sequence[str], None] = '50c899d2e488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('appointment_time', sa.TIMESTAMP(timezone=True), nullable=False))
    op.drop_column('bookings', 'appoitment_tim')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('appoitment_tim', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'appointment_time')
    # ### end Alembic commands ###
